In [4]:
import pandas
from geopy.geocoders import Nominatim
df6 = pandas.read_csv("http://pythonhow.com/supermarkets.csv")
df6 = df6.set_index("ID")
df6["Continent"]=["America","America","America","America","America","America"]
df6["Continent"] = df6.shape[0]*["America"]
df6["Continent"] = "North " + df6["Continent"]
df6_t=df6.T
df6_t[7]=["3157 Dallas Ct", "Santa Clara", "CA 95051", "USA", "John", "1", "North America"]
df6=df6_t.T
nom = Nominatim(scheme='http')
nom.geocode("3157 Dallas Ct, Santa Clara, CA 95051")

Location(Dallas Court, Santa Clara, Santa Clara County, California, 95051, United States of America, (37.3550092, -121.9842338, 0.0))

In [5]:
df6["Address"]=df6["Address"]+" "+df6["City"]+" "+df6["State"]+" "+df6["Country"]
df6

,Address,City,State,Country,Name,Employees,Continent
ID,,,,,,,
1,3666 21st St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Madeira,8,North America
2,735 Dolores St San Francisco CA 94119 USA,San Francisco,CA 94119,USA,Bready Shop,15,North America
3,332 Hill St San Francisco California 94114 USA,San Francisco,California 94114,USA,Super River,25,North America
4,3995 23rd St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Ben's Shop,10,North America
5,1056 Sanchez St San Francisco California USA,San Francisco,California,USA,Sanchez,12,North America
6,551 Alvarado St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Richvalley,20,North America
7,3157 Dallas Ct Santa Clara CA 95051 USA,Santa Clara,CA 95051,USA,John,1,North America

In [6]:
df6=df6.drop("Continent",1)
df6

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St San Francisco CA 94119 USA,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St San Francisco California 94114 USA,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St San Francisco California USA,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Richvalley,20
7,3157 Dallas Ct Santa Clara CA 95051 USA,Santa Clara,CA 95051,USA,John,1

In [11]:
df6["Address"].apply(nom.geocode)

ID
1    (21st Street, Castro District, SF, California,...
2                                                 None
3    (Hill Street, Noe Valley, SF, California, 9411...
4    (3995, 23rd Street, Noe Valley, SF, California...
5    (Sanchez Street, Noe Valley, SF, California, 9...
6    (Alvarado Street, Noe Valley, SF, California, ...
7    (Dallas Court, Santa Clara, Santa Clara County...
Name: Address, dtype: object

In [12]:
df6["Coordinates"]=df6["Address"].apply(nom.geocode)
df6

,Address,City,State,Country,Name,Employees,Coordinates
ID,,,,,,,
1,3666 21st St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Madeira,8,"(21st Street, Castro District, SF, California,..."
2,735 Dolores St San Francisco CA 94119 USA,San Francisco,CA 94119,USA,Bready Shop,15,None
3,332 Hill St San Francisco California 94114 USA,San Francisco,California 94114,USA,Super River,25,"(Hill Street, Noe Valley, SF, California, 9411..."
4,3995 23rd St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Ben's Shop,10,"(3995, 23rd Street, Noe Valley, SF, California..."
5,1056 Sanchez St San Francisco California USA,San Francisco,California,USA,Sanchez,12,"(Sanchez Street, Noe Valley, SF, California, 9..."
6,551 Alvarado St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Richvalley,20,"(Alvarado Street, Noe Valley, SF, California, ..."
7,3157 Dallas Ct Santa Clara CA 95051 USA,Santa Clara,CA 95051,USA,John,1,"(Dallas Court, Santa Clara, Santa Clara County..."

In [13]:
df6.Coordinates[7]

Location(Dallas Court, Santa Clara, Santa Clara County, California, 95051, United States of America, (37.3550092, -121.9842338, 0.0))

In [14]:
df6["Latitude"]=df6["Coordinates"].apply(lambda x: x.latitude if x != None else None)
df6["Longitude"]=df6["Coordinates"].apply(lambda x: x.longitude if x != None else None)
df6

,Address,City,State,Country,Name,Employees,Coordinates,Latitude,Longitude
ID,,,,,,,,,
1,3666 21st St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Madeira,8,"(21st Street, Castro District, SF, California,...",37.755237,-122.440180
2,735 Dolores St San Francisco CA 94119 USA,San Francisco,CA 94119,USA,Bready Shop,15,None,NaN,NaN
3,332 Hill St San Francisco California 94114 USA,San Francisco,California 94114,USA,Super River,25,"(Hill Street, Noe Valley, SF, California, 9411...",37.755689,-122.427829
4,3995 23rd St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Ben's Shop,10,"(3995, 23rd Street, Noe Valley, SF, California...",37.752965,-122.431714
5,1056 Sanchez St San Francisco California USA,San Francisco,California,USA,Sanchez,12,"(Sanchez Street, Noe Valley, SF, California, 9...",37.748362,-122.429346
6,551 Alvarado St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Richvalley,20,"(Alvarado Street, Noe Valley, SF, California, ...",37.753666,-122.434440
7,3157 Dallas Ct Santa Clara CA 95051 USA,Santa Clara,CA 95051,USA,John,1,"(Dallas Court, Santa Clara, Santa Clara County...",37.355009,-121.984234

In [17]:
df6.loc[7,"Latitude":"Longitude"]

Latitude      37.355
Longitude   -121.984
Name: 7, dtype: object

In [18]:
df6=df6.drop("Coordinates",1)

ValueError: labels ['Coordinates'] not contained in axis

In [19]:
print(df6)

                                             Address            City  \
ID
1          3666 21st St San Francisco  CA 94114  USA   San Francisco
2        735 Dolores St San Francisco  CA 94119  USA   San Francisco
3    332 Hill St  San Francisco California 94114 USA   San Francisco
4          3995 23rd St  San Francisco  CA 94114 USA   San Francisco
5       1056 Sanchez St San Francisco California USA   San Francisco
6         551 Alvarado St San Francisco CA 94114 USA   San Francisco
7            3157 Dallas Ct Santa Clara CA 95051 USA     Santa Clara

               State Country          Name Employees   Latitude   Longitude
ID
1           CA 94114     USA       Madeira         8  37.755237 -122.440180
2           CA 94119     USA   Bready Shop        15        NaN         NaN
3   California 94114     USA   Super River        25  37.755689 -122.427829
4           CA 94114     USA    Ben's Shop        10  37.752965 -122.431714
5         California     USA       Sanchez        12  37.748362 -122.429346
6           CA 94114     USA    Richvalley        20  37.753666 -122.434440
7           CA 95051     USA          John         1  37.355009 -121.984234

df6