In [2]:
import pandas
from geopy.geocoders import Nominatim
df6 = pandas.read_csv("http://pythonhow.com/supermarkets.csv")
df6 = df6.set_index("ID")
df6["Continent"]=["America","America","America","America","America","America"]
df6["Continent"] = df6.shape[0]*["America"]
df6["Continent"] = "North " + df6["Continent"]
df6_t=df6.T
df6_t[7]=["3157 Dallas Ct", "Santa Clara", "CA 95051", "USA", "John", "1", "North America"]
df6=df6_t.T
nom = Nominatim(scheme='http')
nom.geocode("3157 Dallas Ct, Santa Clara, CA 95051")

Location(3157, Dallas Court, Santa Clara, Santa Clara County, California, 95051, United States of America, (37.3550665714286, -121.984528428571, 0.0))

In [3]:
df6["Address"]=df6["Address"]+" "+df6["City"]+" "+df6["State"]+" "+df6["Country"]
df6

,Address,City,State,Country,Name,Employees,Continent
ID,,,,,,,
1,3666 21st St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Madeira,8,North America
2,735 Dolores St San Francisco CA 94119 USA,San Francisco,CA 94119,USA,Bready Shop,15,North America
3,332 Hill St San Francisco California 94114 USA,San Francisco,California 94114,USA,Super River,25,North America
4,3995 23rd St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Ben's Shop,10,North America
5,1056 Sanchez St San Francisco California USA,San Francisco,California,USA,Sanchez,12,North America
6,551 Alvarado St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Richvalley,20,North America
7,3157 Dallas Ct Santa Clara CA 95051 USA,Santa Clara,CA 95051,USA,John,1,North America

In [5]:
df6=df6.drop("Continent",1)
df6

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St San Francisco CA 94119 USA,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St San Francisco California 94114 USA,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St San Francisco California USA,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Richvalley,20
7,3157 Dallas Ct Santa Clara CA 95051 USA,Santa Clara,CA 95051,USA,John,1

In [7]:
df6["Coordinates"]=df6["Address"].apply(nom.geocode)
df6

,Address,City,State,Country,Name,Employees,Coordinates
ID,,,,,,,
1,3666 21st St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Madeira,8,None
2,735 Dolores St San Francisco CA 94119 USA,San Francisco,CA 94119,USA,Bready Shop,15,None
3,332 Hill St San Francisco California 94114 USA,San Francisco,California 94114,USA,Super River,25,"(332, Hill Street, Liberty Street Historic Dis..."
4,3995 23rd St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Ben's Shop,10,None
5,1056 Sanchez St San Francisco California USA,San Francisco,California,USA,Sanchez,12,"(1056, Sanchez Street, Noe Valley, SF, Califor..."
6,551 Alvarado St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Richvalley,20,"(551, Alvarado Street, Noe Valley, SF, Califor..."
7,3157 Dallas Ct Santa Clara CA 95051 USA,Santa Clara,CA 95051,USA,John,1,"(3157, Dallas Court, Santa Clara, Santa Clara ..."

In [14]:
df6.Coordinates[7]

Location(3157, Dallas Court, Santa Clara, Santa Clara County, California, 95051, United States of America, (37.3550665714286, -121.984528428571, 0.0))

In [21]:
df6["Latitude"]=df6["Coordinates"].apply(lambda x: x.latitude if x != None else None)
df6["Longitude"]=df6["Coordinates"].apply(lambda x: x.longitude if x != None else None)
df6

,Address,City,State,Country,Name,Employees,Coordinates,Latitude,Longitude
ID,,,,,,,,,
1,3666 21st St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Madeira,8,None,NaN,NaN
2,735 Dolores St San Francisco CA 94119 USA,San Francisco,CA 94119,USA,Bready Shop,15,None,NaN,NaN
3,332 Hill St San Francisco California 94114 USA,San Francisco,California 94114,USA,Super River,25,"(332, Hill Street, Liberty Street Historic Dis...",37.755725,-122.428601
4,3995 23rd St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Ben's Shop,10,None,NaN,NaN
5,1056 Sanchez St San Francisco California USA,San Francisco,California,USA,Sanchez,12,"(1056, Sanchez Street, Noe Valley, SF, Califor...",37.752146,-122.429815
6,551 Alvarado St San Francisco CA 94114 USA,San Francisco,CA 94114,USA,Richvalley,20,"(551, Alvarado Street, Noe Valley, SF, Califor...",37.753673,-122.433220
7,3157 Dallas Ct Santa Clara CA 95051 USA,Santa Clara,CA 95051,USA,John,1,"(3157, Dallas Court, Santa Clara, Santa Clara ...",37.355067,-121.984528

In [22]:
df6.loc[7,"Latitude":"Longitude"]

Latitude     37.3551
Longitude   -121.985
Name: 7, dtype: object